trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

stages:

# -----------------------
# BUILD STAGE
# -----------------------
- stage: Build
  displayName: Build Stage

  jobs:
  - job: BuildJob
    displayName: Build EMS Solution

    steps:

    - task: UseDotNet@2
      displayName: Install .NET 8 SDK
      inputs:
        packageType: 'sdk'
        version: '8.0.x'

    - task: DotNetCoreCLI@2
      displayName: Restore Packages
      inputs:
        command: restore
        projects: '**/*.sln'

    - task: DotNetCoreCLI@2
      displayName: Build Solution
      inputs:
        command: build
        projects: '**/*.sln'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Publish API
      inputs:
        command: publish
        publishWebProjects: false
        projects: '**/EMS.API.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: Publish Artifact
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'EMS_API'

# -----------------------
# DEV STAGE
# -----------------------
- stage: DEV
  displayName: DEV Environment
  dependsOn: Build

  variables:
  - group: EMS-DEV

  jobs:
  - deployment: DeployDEV
    displayName: Deploy To DEV
    environment: DEV

    strategy:
      runOnce:
        deploy:
          steps:
         - script: |
    echo "Deploying EMS to DEV Environment"
    echo "Environment = $(EnvironmentName)"
    echo "Issuer = $(JwtIssuer)"
    echo "Audience = $(JwtAudience)"

# -----------------------
# QA STAGE
# -----------------------
- stage: QA
  displayName: QA Environment
  dependsOn: DEV

  variables:
  - group: EMS-QA

  jobs:
  - deployment: DeployQA
    displayName: Deploy To QA
    environment: QA

    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
    echo "Deploying EMS to QA Environment"
    echo "Environment = $(EnvironmentName)"
    echo "Issuer = $(JwtIssuer)"
    echo "Audience = $(JwtAudience)"

# -----------------------
# PROD STAGE
# -----------------------
- stage: PROD
  displayName: PROD Environment
  dependsOn: QA

  variables:
  - group: EMS-PROD

  jobs:
  - deployment: DeployPROD
    displayName: Deploy To PROD
    environment: PROD

    strategy:
      runOnce:
        deploy:
          steps:
         - script: |
    echo "Deploying EMS to PROD Environment"
    echo "Environment = $(EnvironmentName)"
    echo "Issuer = $(JwtIssuer)"
    echo "Audience = $(JwtAudience)"
